# Generated by Django 5.2.8 on 2025-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_commentproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentproduct',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='in_stock',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], null=True, verbose_name='موجود در انیار'),
        ),
    ]
