# Generated by Django 5.2.8 on 2025-12-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_commentproduct_options_productmodel_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='avg_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_rating', to='products.commentproduct'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rating_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_count', to='products.commentproduct'),
        ),
    ]
