# Generated by Django 5.2.8 on 2025-12-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_commentproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.productmodel'),
        ),
    ]
