# Generated by Django 5.2.3 on 2025-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productmodel_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.categorymodel', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='images',
            field=models.ManyToManyField(related_name='products', to='products.imagemodel', verbose_name='عکس ها'),
        ),
    ]
