# Generated by Django 5.2.9 on 2025-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodel_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
