# Generated by Django 5.2.9 on 2025-12-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
    ]
