# Generated by Django 5.2.9 on 2025-12-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productmodel_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=2, null=True, verbose_name='تعداد در انبار'),
        ),
    ]
