# Generated by Django 5.2.9 on 2026-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_quantity_productmodel_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
